---
- name: htpasswd | install python-passlib (for htpasswd mgmt)
  yum:
    name: python-passlib
    state: present
  when: apache_use_htpasswd|bool

- name: htpasswd | create htpasswd file
  htpasswd:
    destfile: "{{ item.destfile }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state|default('present') }}"
  with_items: '{{ apache_htpasswd_entries }}'
  when: apache_use_htpasswd|bool
